// <auto-generated />
using System;
using FolhaDePagamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolhaDePagamento.Migrations
{
    [DbContext(typeof(FolhaDePagamentoDbContext))]
    [Migration("20231027175556_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FolhaDePagamento.Models.AdicionaisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodAdicional")
                        .HasColumnType("INTEGER");

                    b.Property<float>("DecimoTerceiro")
                        .HasColumnType("REAL");

                    b.Property<int>("HorasExtras")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Adicionais");
                });

            modelBuilder.Entity("FolhaDePagamento.Models.DescontoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodDesconto")
                        .HasColumnType("INTEGER");

                    b.Property<float>("FGTS")
                        .HasColumnType("REAL");

                    b.Property<float>("Irrf")
                        .HasColumnType("REAL");

                    b.Property<float>("TaxaInss")
                        .HasColumnType("REAL");

                    b.Property<float>("Vt")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Desconto");
                });

            modelBuilder.Entity("FolhaDePagamento.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CPF")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CertNascimento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<float>("Comissao")
                        .HasColumnType("REAL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("HorasTrabalhadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("PIS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RG")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Salario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("FolhaDePagamento.Models.GerenteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CPF")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CertNascimento")
                        .HasColumnType("TEXT");

                    b.Property<float>("Comissao")
                        .HasColumnType("REAL");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("HorasTrabalhadas")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PIS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RG")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Salario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Gerente");
                });

            modelBuilder.Entity("FolhaDePagamento.Models.HoleriteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodHolerite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataReferencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holerite");
                });
#pragma warning restore 612, 618
        }
    }
}
